version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: npm run start:dev
    env_file:
      - .env
    links: 
      - postgres
    depends_on:
      - redis
      - postgres
  redis:
    container_name: redis
    image: redis:5
    ports: 
      - ${REDIS_PORT}:${REDIS_PORT}
  postgres:
    container_name: smolprodb
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_HOST: ${DB_HOST}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT}:${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: